# Import file generated by the installer
. /usr/local/potabi/config.conf

# Destroy zpool if exists
zpool destroy -f install-potabi | true

# Mount release
mkdir -pv /mnt/install
gpart add -t freebsd-boot -s 128k -l boot ${disk}
gpart add -t freebsd-zfs -l system ${disk}
zpool create install-potabi /dev/${disk}p2
zfs set mountpoint=/mnt/install install-potabi
zfs set compression=gzip-6 install-potabi

# Unpack base and kernel into directory
cd /mnt/install
tar xvf /usr/local/potabi/base.txz
tar xvf /usr/local/potabi/kernel.txz
gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ${disk}

# Unmount at end of script
zfs unmount -f /mnt/install
zpool destroy -f install-potabi
